apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\toder\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mastodon
  name: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mastodon
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\toder\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-default: "true"
        io.kompose.service: mastodon
    spec:
      containers:
        - image: iuliaaaaa/tutoringplatform:mastodon
          name: mastodon
          ports:
            - containerPort: 29019
              hostPort: 29019
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
