apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\toder\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mastodon
  name: mastodon
spec:
  ports:
    - name: "29019"
      port: 29019
      targetPort: 29019
  selector:
    io.kompose.service: mastodon
status:
  loadBalancer: {}
